name:                AoC2015
version:             0.1.0.0
github:              "herrmanno/AoC2015"
license:             BSD3
author:              "Oliver Herrmann"
maintainer:          "o.herrmann92@gmail.com"
copyright:           "Oliver Herrmann 2021"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/herrmanno/AoC2015#readme>

dependencies:
- base >= 4.7 && < 5
- text
- split
- containers
- bytestring
- base16-bytestring
- cryptohash-md5

default-extensions:
- FlexibleContexts
- NamedFieldPuns
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes

library:
  source-dirs: src

executables:
  AoC2015-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    - -O2
    dependencies:
    - AoC2015

tests:
  AoC2015-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    dependencies:
    - AoC2015
    - hspec
